In [1]:
import pandas as pd
import random
from datetime import datetime, timedelta

In [2]:
# Function to generate unique ID
def generate_unique_id(existing_ids):
    while True:
        new_id = random.randint(1, 10000)
        if new_id not in existing_ids:
            existing_ids.add(new_id)
            return new_id

# Function to generate a random date between two given dates
def random_date(start_date, end_date):
    return start_date + timedelta(
        seconds=random.randint(0, int((end_date - start_date).total_seconds()))
    )

In [3]:
# Generate branch_details data
branches = []
branch_codes = set()
for i in range(1, 501):
    branch_code = f"B{i:03}"
    branch_codes.add(branch_code)

    # Hanya ambil tanggal untuk operation_start_date dan last_renovation_date
    operation_start_date = random_date(datetime(2000, 1, 1), datetime(2024, 1, 1)).date()
    last_renovation_date = random_date(datetime(2000, 1, 1), datetime(2024, 1, 1)).date()

    branches.append({
        "branch_code": branch_code,
        "branch_name": f"Branch_{i}",
        "region_id": random.randint(1, 3),
        "operation_start_date": operation_start_date,
        "is_active": random.choice([1, 0]),
        "max_capacity": random.randint(100, 1000),
        "last_renovation_date": last_renovation_date
    })

branch_details = pd.DataFrame(branches)

In [4]:
branch_details.head()

,branch_code,branch_name,region_id,operation_start_date,is_active,max_capacity,last_renovation_date
0,B001,Branch_1,2,2002-06-10,0,166,2006-02-13
1,B002,Branch_2,2,2009-03-16,0,324,2000-08-11
2,B003,Branch_3,3,2012-09-13,1,692,2014-08-19
3,B004,Branch_4,3,2010-03-22,1,701,2000-04-05
4,B005,Branch_5,2,2014-10-18,0,310,2013-03-06

In [5]:
# Generate staff_records data
staff = []
staff_ids = set()
for i in range(1, 501):
    staff_id = generate_unique_id(staff_ids)
    branch_code = random.choice(list(branch_codes))
    join_date = random_date(datetime(2015, 1, 1), datetime(2023, 1, 1))

    # Mengatur resignation_date jika random() > 0.7
    resignation_date = join_date + timedelta(days=random.randint(30, 2000)) if random.random() > 0.7 else None

    # Mengubah resignation_date menjadi tanggal (bukan datetime)
    if resignation_date is not None:
        resignation_date = resignation_date.date()
    else:
        resignation_date = '0'

    # Generate supervisor_id, pastikan tidak ada NaN
    supervisor_id = generate_unique_id(staff_ids)

    staff.append({
        "staff_id": staff_id,
        "branch_code": branch_code,
        "join_date": join_date.date(),
        "role_code": f"R{random.randint(1, 5):02}",
        "base_salary": round(random.uniform(20000, 80000), 2),
        "supervisor_id": supervisor_id,
        "resignation_date": resignation_date,
        "performance_score": round(random.uniform(1.0, 5.0), 2)
    })

staff_records = pd.DataFrame(staff)

In [6]:
staff_records.head()

,staff_id,branch_code,join_date,role_code,base_salary,supervisor_id,resignation_date,performance_score
0,2582,B331,2015-08-07,R04,37690.60,8917,2016-06-02,2.41
1,814,B168,2020-10-31,R05,37325.14,1481,0,4.85
2,5280,B206,2017-10-16,R02,54722.89,1764,2023-03-24,1.33
3,5202,B380,2017-07-10,R01,29308.53,7581,0,3.91
4,9834,B176,2020-12-11,R05,77259.05,5854,0,4.81

In [7]:
# Generate product_hierarchy data
products = []
product_codes = set()
for i in range(1, 501):
    product_code = f"P{i:06}"
    product_codes.add(product_code)
    products.append({
        "product_code": product_code,
        "product_name": f"Product_{i}",
        "category_l1": random.choice(["Men's Clothing", "Women's Clothing", "Children's Clothing"]),
        "category_l2": random.choice(["Shirts", "Pants", "Jackets", "Sweaters", "T-Shirts"]),
        "category_l3": random.choice(["Casual", "Formal", "Sporty", "Party", "Outdoor"]),
        "unit_cost": round(random.uniform(10, 100), 2),
        "unit_price": round(random.uniform(20, 150), 2),
        "supplier_id": f"SUP{random.randint(1, 5):02}",
        "minimum_stock": random.randint(5, 50),
        "is_perishable": random.choice([1, 0])
    })
product_hierarchy = pd.DataFrame(products)

In [8]:
product_hierarchy.head()

,product_code,product_name,category_l1,category_l2,category_l3,unit_cost,unit_price,supplier_id,minimum_stock,is_perishable
0,P000001,Product_1,Men's Clothing,Jackets,Sporty,34.31,50.89,SUP03,6,1
1,P000002,Product_2,Women's Clothing,Jackets,Casual,99.61,126.50,SUP01,11,1
2,P000003,Product_3,Women's Clothing,Shirts,Outdoor,23.94,28.92,SUP03,15,1
3,P000004,Product_4,Women's Clothing,Jackets,Casual,35.73,130.12,SUP02,47,1
4,P000005,Product_5,Children's Clothing,Jackets,Party,27.87,101.06,SUP04,40,1

In [9]:
# Generate inventory_movements data
movements = []
movement_ids = set()
for i in range(1, 501):
    movement_id = generate_unique_id(movement_ids)
    product_code = random.choice(list(product_codes))
    branch_code = random.choice(list(branch_codes))
    transaction_type = random.choice(["IN", "OUT", "ADJ", "RTN", "EXP"])

    # Hanya ambil tanggal untuk transaction_date
    transaction_date = random_date(datetime(2000, 1, 1), datetime(2024, 1, 1)).date()

    # Isi expiry_date untuk semua transaksi
    expiry_date = random_date(datetime(2000, 1, 1), datetime(2024, 1, 1)).date()

    movements.append({
        "movement_id": movement_id,
        "product_code": product_code,
        "branch_code": branch_code,
        "transaction_type": transaction_type,
        "quantity": random.randint(1, 1000),
        "transaction_date": transaction_date,
        "batch_number": f"BATCH{i:05}",
        "expiry_date": expiry_date,
        "unit_cost_at_time": round(random.uniform(10, 100), 2)
    })

inventory_movements = pd.DataFrame(movements)

In [10]:
inventory_movements.head()

,movement_id,product_code,branch_code,transaction_type,quantity,transaction_date,batch_number,expiry_date,unit_cost_at_time
0,1167,P000175,B185,OUT,294,2020-12-24,BATCH00001,2002-03-24,84.72
1,3396,P000052,B026,ADJ,598,2013-03-30,BATCH00002,2022-03-19,42.80
2,821,P000424,B344,ADJ,873,2022-12-26,BATCH00003,2020-09-03,47.01
3,4217,P000069,B026,IN,166,2018-09-09,BATCH00004,2008-10-26,12.16
4,1197,P000417,B093,ADJ,987,2004-08-20,BATCH00005,2010-01-24,46.11

In [11]:
# Generate sales_transactions data
sales = []
transaction_ids = set()
for i in range(1, 501):
    transaction_id = generate_unique_id(transaction_ids)
    branch_code = random.choice(list(branch_codes))
    staff_id = random.choice(list(staff_ids))

    # Ambil hanya tanggal untuk transaction_date
    transaction_date = random_date(datetime(2000, 1, 1), datetime(2024, 1, 1)).date()

    sales.append({
        "transaction_id": transaction_id,
        "branch_code": branch_code,
        "transaction_date": transaction_date,
        "staff_id": staff_id,
        "payment_method": random.choice(["Cash", "Card", "Online"]),
        "total_amount": round(random.uniform(50, 1000), 2),
        "discount_amount": round(random.uniform(0, 50), 2),
        "loyalty_points_earned": random.randint(0, 100),
        "loyalty_points_redeemed": random.randint(0, 50),
        "customer_id": f"CUST{random.randint(1, 100):05}"
    })

sales_transactions = pd.DataFrame(sales)

In [12]:
sales_transactions.head()

,transaction_id,branch_code,transaction_date,staff_id,payment_method,total_amount,discount_amount,loyalty_points_earned,loyalty_points_redeemed,customer_id
0,2330,B365,2002-02-22,5439,Online,831.45,23.85,96,21,CUST00017
1,5427,B149,2019-07-02,5831,Cash,502.79,16.77,2,11,CUST00041
2,2550,B042,2018-07-15,6392,Card,881.92,7.13,12,9,CUST00046
3,8857,B216,2008-02-27,2592,Cash,838.93,40.09,12,28,CUST00077
4,8187,B163,2006-03-08,5439,Cash,962.76,47.03,50,29,CUST00045

In [13]:
# Generate sales_line_items data
line_items = []
for i in range(1, 501):
    transaction_id = random.choice(list(transaction_ids))
    product_code = random.choice(list(product_codes))

    quantity = random.randint(1, 100)
    unit_price = round(random.uniform(500, 5000), 2)

    discount_percentage = round(random.uniform(0, 40), 2)
    total_line_amount = quantity * unit_price * (1 - discount_percentage / 100)

    line_items.append({
        "transaction_id": transaction_id,
        "line_number": i,
        "product_code": product_code,
        "quantity": quantity,
        "unit_price_at_time": unit_price,
        "discount_percentage": discount_percentage,
        "total_line_amount": round(total_line_amount, 2)
    })

sales_line_items = pd.DataFrame(line_items)

# Format pandas untuk menghindari scientific notation
pd.options.display.float_format = '{:,.2f}'.format

In [14]:
sales_line_items.head()

,transaction_id,line_number,product_code,quantity,unit_price_at_time,discount_percentage,total_line_amount
0,7312,1,P000034,92,"4,152.28",21.97,"298,082.22"
1,5203,2,P000400,14,"4,049.44",13.17,"49,225.80"
2,5257,3,P000264,75,"4,990.74",19.35,"301,877.39"
3,7456,4,P000117,42,"2,672.90",28.41,"80,368.22"
4,8062,5,P000201,20,580.72,24.48,"8,771.19"

## Calculate inventory turnover metrics per branch

In [21]:
import sqlite3
import pandas as pd

# Buat koneksi SQLite sementara
conn = sqlite3.connect(":memory:")

# Simpan data DataFrame ke SQLite
branch_details.to_sql("branch_details", conn, if_exists="replace", index=False)
inventory_movements.to_sql("inventory_movements", conn, if_exists="replace", index=False)

# Query SQL untuk menampilkan informasi yang diminta
query = """
WITH max_date AS (
    SELECT MAX(transaction_date) AS max_transaction_date
    FROM inventory_movements
),
stock_summary AS (
    SELECT
        bd.branch_name,
        im.branch_code,
        -- Total barang yang masuk (IN)
        SUM(CASE WHEN im.transaction_type = 'IN' THEN im.quantity ELSE 0 END) AS total_incoming_stock,
        -- Total barang yang keluar (OUT)
        SUM(CASE WHEN im.transaction_type = 'OUT' THEN im.quantity ELSE 0 END) AS total_outgoing_stock,
        -- Total penyesuaian stok (ADJ)
        SUM(CASE WHEN im.transaction_type = 'ADJ' THEN im.quantity ELSE 0 END) AS total_adjustment_stock,
        -- Total barang kadaluarsa (EXP)
        SUM(CASE WHEN im.transaction_type = 'EXP' THEN im.quantity ELSE 0 END) AS total_expired_stock,
        -- Total barang yang dikembalikan (RTN)
        SUM(CASE WHEN im.transaction_type = 'RTN' THEN im.quantity ELSE 0 END) AS total_returned_stock,
        -- Perhitungan stock level saat ini (penjumlahan dan pengurangan yang sesuai)
        SUM(CASE
            WHEN im.transaction_type = 'IN' THEN im.quantity  -- Barang masuk
            WHEN im.transaction_type = 'OUT' THEN -im.quantity  -- Barang keluar
            WHEN im.transaction_type = 'ADJ' THEN im.quantity  -- Penyesuaian stok
            WHEN im.transaction_type = 'RTN' THEN im.quantity  -- Retur barang (menambah stok)
            WHEN im.transaction_type = 'EXP' THEN -im.quantity  -- Barang kadaluarsa
            ELSE 0
        END) AS current_stock_level
    FROM
        inventory_movements im
    JOIN
        branch_details bd ON im.branch_code = bd.branch_code
    CROSS JOIN
        max_date
    WHERE
        im.transaction_date >= DATE(max_date.max_transaction_date, '-3 months')  -- Menggunakan max(transaction_date)
    GROUP BY
        bd.branch_name, im.branch_code
),
stock_turnover AS (
    SELECT
        branch_name,
        branch_code,
        total_incoming_stock,
        total_outgoing_stock,
        total_adjustment_stock,
        total_expired_stock,
        total_returned_stock,
        current_stock_level,
        -- Perhitungan stock turnover rate dengan rumus yang disesuaikan
        CASE
            WHEN total_incoming_stock = 0 THEN 0  -- Menghindari pembagian dengan nol
            ELSE CAST(total_outgoing_stock + total_adjustment_stock - total_expired_stock + total_returned_stock AS FLOAT) / total_incoming_stock
        END AS stock_turnover_rate
    FROM
        stock_summary
)
SELECT
    branch_name,
    total_incoming_stock,
    total_outgoing_stock,
    current_stock_level,
    stock_turnover_rate,
    total_expired_stock AS number_of_expired_items
FROM
    stock_turnover
ORDER BY
    stock_turnover_rate DESC;
"""

# Jalankan query dan simpan hasilnya ke DataFrame
result_inventory_turnover = pd.read_sql_query(query, conn)

pd.set_option("display.max_rows", None)

# Tampilkan hasil
print(result_inventory_turnover)

# Tutup koneksi SQLite
conn.close()

  branch_name  total_incoming_stock  total_outgoing_stock  \
0  Branch_135                     0                     0
1  Branch_262                     0                     0
2  Branch_341                     0                     0
3  Branch_345                     0                     0
4    Branch_4                     0                     0
5   Branch_72                    62                     0

   current_stock_level  stock_turnover_rate  number_of_expired_items
0                  132                 0.00                        0
1                  856                 0.00                        0
2                  670                 0.00                        0
3                  902                 0.00                        0
4                  125                 0.00                        0
5                 -457                -8.37                      519

In [22]:
result_inventory_turnover.head(10)

,branch_name,total_incoming_stock,total_outgoing_stock,current_stock_level,stock_turnover_rate,number_of_expired_items
0,Branch_135,0,0,132,0.00,0
1,Branch_262,0,0,856,0.00,0
2,Branch_341,0,0,670,0.00,0
3,Branch_345,0,0,902,0.00,0
4,Branch_4,0,0,125,0.00,0
5,Branch_72,62,0,-457,-8.37,519

## Analyze staff performance and sales

In [23]:
import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Creating the necessary tables (simplified for this example)
branch_details.to_sql("branch_details", conn, index=False, if_exists="replace")
staff_records.to_sql("staff_records", conn, index=False, if_exists="replace")
sales_transactions.to_sql("sales_transactions", conn, index=False, if_exists="replace")
sales_line_items.to_sql("sales_line_items", conn, index=False, if_exists="replace")

# SQL query to get the desired results
query = """
SELECT
    s.staff_id,
    b.branch_name,
    COUNT(st.transaction_id) AS number_of_transactions,
    SUM(st.total_amount) AS total_sales_amount,
    AVG(st.total_amount) AS average_transaction_value,
    s.performance_score
FROM
    staff_records s
JOIN
    branch_details b ON s.branch_code = b.branch_code
LEFT JOIN
    sales_transactions st ON s.staff_id = st.staff_id
WHERE
    s.resignation_date = '0'  -- Active staff (no resignation)
GROUP BY
    s.staff_id, b.branch_name, s.performance_score
"""

# Execute the query and load it into a DataFrame
result_staff_performance = pd.read_sql(query, conn)

# Close the connection
conn.close()

In [24]:
result_staff_performance

,staff_id,branch_name,number_of_transactions,total_sales_amount,average_transaction_value,performance_score
0,9,Branch_174,0,NaN,NaN,1.36
1,35,Branch_140,2,"1,782.74",891.37,1.36
2,47,Branch_316,0,NaN,NaN,2.25
3,129,Branch_224,0,NaN,NaN,1.74
4,182,Branch_489,1,354.48,354.48,2.21
5,223,Branch_280,0,NaN,NaN,2.16
6,227,Branch_22,1,414.52,414.52,1.92
7,249,Branch_304,2,"1,206.77",603.38,2.06
8,274,Branch_17,1,59.27,59.27,1.98
9,299,Branch_240,2,"1,049.61",524.81,4.59
10,329,Branch_255,0,NaN,NaN,2.14
11,373,Branch_257,1,436.88,436.88,1.64
12,397,Branch_430,0,NaN,NaN,1.56
13,455,Branch_184,0,NaN,NaN,1.03
14,550,Branch_452,1,629.55,629.55,1.87
15,578,Branch_80,1,549.64,549.64,1.14
16,619,Branch_313,0,NaN,NaN,3.88
17,684,Branch_178,1,261.29,261.29,3.51
18,690,Branch_355,0,NaN,NaN,2.79
19,706,Branch_259,0,NaN,NaN,4.38
20,804,Branch_31,1,732.80,732.80,4.27
21,814,Branch_168,0,NaN,NaN,4.85
22,824,Branch_219,1,221.70,221.70,4.95
23,844,Branch_263,0,NaN,NaN,4.81
24,854,Branch_251,0,NaN,NaN,2.93
25,875,Branch_229,2,370.96,185.48,2.78
26,893,Branch_213,1,337.01,337.01,4.13
27,897,Branch_209,0,NaN,NaN,2.85
28,910,Branch_446,0,NaN,NaN,3.28
29,920,Branch_426,1,421.61,421.61,4.25
30,947,Branch_75,0,NaN,NaN,2.31
31,996,Branch_255,1,367.34,367.34,2.54
32,1061,Branch_478,0,NaN,NaN,3.80
33,1072,Branch_252,1,193.41,193.41,1.19
34,1074,Branch_291,1,82.06,82.06,4.77
35,1079,Branch_236,1,228.00,228.00,3.91
36,1104,Branch_169,0,NaN,NaN,3.69
37,1109,Branch_354,1,380.57,380.57,2.86
38,1125,Branch_433,0,NaN,NaN,1.41
39,1128,Branch_433,0,NaN,NaN,4.72
40,1214,Branch_409,0,NaN,NaN,4.33
41,1242,Branch_56,3,"1,767.45",589.15,2.29
42,1248,Branch_224,0,NaN,NaN,1.52
43,1253,Branch_499,0,NaN,NaN,2.53
44,1260,Branch_447,1,826.00,826.00,3.72
45,1294,Branch_179,0,NaN,NaN,2.28
46,1371,Branch_463,0,NaN,NaN,3.26
47,1421,Branch_155,0,NaN,NaN,4.11
48,1495,Branch_213,1,593.21,593.21,4.01
49,1496,Branch_381,0,NaN,NaN,2.73
50,1519,Branch_406,1,141.54,141.54,2.06
51,1576,Branch_9,0,NaN,NaN,3.88
52,1583,Branch_302,0,NaN,NaN,2.94
53,1585,Branch_333,2,853.60,426.80,4.84
54,1586,Branch_27,2,"1,024.10",512.05,4.29
55,1592,Branch_53,1,473.11,473.11,3.93
56,1631,Branch_498,2,991.60,495.80,3.90
57,1638,Branch_32,1,774.82,774.82,1.25
58,1670,Branch_372,0,NaN,NaN,2.64
59,1704,Branch_23,0,NaN,NaN,2.00
60,1744,Branch_267,0,NaN,NaN,3.91
61,1887,Branch_492,0,NaN,NaN,4.44
62,1892,Branch_79,1,537.78,537.78,4.11
63,1914,Branch_487,1,812.00,812.00,2.97
64,1929,Branch_138,0,NaN,NaN,3.00
65,1976,Branch_462,0,NaN,NaN,3.06
66,2072,Branch_233,0,NaN,NaN,3.26
67,2104,Branch_134,0,NaN,NaN,1.43
68,2128,Branch_2,0,NaN,NaN,3.14
69,2157,Branch_288,0,NaN,NaN,3.59
70,2160,Branch_413,1,433.83,433.83,4.77
71,2174,Branch_6,0,NaN,NaN,3.40
72,2176,Branch_322,2,"1,815.99",908.00,1.20
73,2221,Branch_42,0,NaN,NaN,2.97
74,2240,Branch_266,0,NaN,NaN,1.04
75,2256,Branch_307,1,485.05,485.05,3.53
76,2283,Branch_395,2,"1,820.51",910.25,1.10
77,2305,Branch_492,1,955.06,955.06,3.73
78,2317,Branch_417,1,625.98,625.98,2.45
79,2332,Branch_455,1,74.95,74.95,3.34
80,2346,Branch_459,0,NaN,NaN,3.67
81,2361,Branch_96,0,NaN,NaN,1.28
82,2376,Branch_499,0,NaN,NaN,3.33
83,2416,Branch_327,0,NaN,NaN,1.78
84,2427,Branch_91,0,NaN,NaN,1.72
85,2435,Branch_385,0,NaN,NaN,2.53
86,2452,Branch_239,2,"1,361.14",680.57,2.84
87,2498,Branch_200,1,478.07,478.07,1.18
88,2517,Branch_384,1,621.70,621.70,2.84
89,2544,Branch_421,2,"1,564.80",782.40,4.34
90,2549,Branch_64,1,737.09,737.09,3.59
91,2564,Branch_482,1,839.06,839.06,2.90
92,2590,Branch_322,1,355.50,355.50,2.98
93,2614,Branch_78,0,NaN,NaN,3.92
94,2622,Branch_296,0,NaN,NaN,3.44
95,2630,Branch_184,0,NaN,NaN,4.77
96,2660,Branch_112,1,534.92,534.92,4.94
97,2669,Branch_416,0,NaN,NaN,2.90
98,2700,Branch_492,2,"1,025.38",512.69,2.13
99,2787,Branch_187,0,NaN,NaN,4.40
100,2805,Branch_128,0,NaN,NaN,4.31
101,2810,Branch_203,1,281.40,281.40,2.22
102,2833,Branch_486,1,857.23,857.23,2.93
103,2853,Branch_206,0,NaN,NaN,1.37
104,2856,Branch_293,3,"2,777.37",925.79,2.21
105,2920,Branch_487,0,NaN,NaN,2.77
106,2955,Branch_57,0,NaN,NaN,4.92
107,2963,Branch_448,1,605.14,605.14,1.92
108,2978,Branch_303,0,NaN,NaN,4.90
109,3091,Branch_478,0,NaN,NaN,2.80
110,3100,Branch_224,0,NaN,NaN,2.98
111,3113,Branch_414,0,NaN,NaN,2.12
112,3142,Branch_406,0,NaN,NaN,4.93
113,3149,Branch_214,0,NaN,NaN,4.36
114,3182,Branch_183,2,"1,314.46",657.23,4.23
115,3214,Branch_306,1,280.85,280.85,4.25
116,3218,Branch_241,0,NaN,NaN,3.45
117,3294,Branch_134,1,805.06,805.06,3.97
118,3331,Branch_267,0,NaN,NaN,2.07
119,3339,Branch_315,0,NaN,NaN,2.80
120,3349,Branch_415,0,NaN,NaN,3.78
121,3399,Branch_471,0,NaN,NaN,3.33
122,3404,Branch_148,1,91.13,91.13,4.81
123,3449,Branch_175,1,981.74,981.74,3.81
124,3459,Branch_65,1,591.23,591.23,4.21
125,3551,Branch_496,2,782.18,391.09,1.97
126,3561,Branch_203,0,NaN,NaN,1.86
127,3586,Branch_85,0,NaN,NaN,2.67
128,3599,Branch_183,0,NaN,NaN,1.74
129,3658,Branch_284,1,854.64,854.64,2.29
130,3678,Branch_155,0,NaN,NaN,1.32
131,3688,Branch_280,0,NaN,NaN,2.80
132,3715,Branch_368,0,NaN,NaN,1.80
133,3746,Branch_251,0,NaN,NaN,2.65
134,3786,Branch_160,0,NaN,NaN,2.95
135,3800,Branch_64,0,NaN,NaN,4.68
136,3821,Branch_309,1,791.00,791.00,3.71
137,3835,Branch_270,1,546.48,546.48,1.69
138,3836,Branch_312,1,357.69,357.69,1.20
139,3841,Branch_186,0,NaN,NaN,2.91
140,3852,Branch_405,1,502.05,502.05,1.62
141,3898,Branch_305,0,NaN,NaN,1.93
142,3911,Branch_211,0,NaN,NaN,1.73
143,3916,Branch_438,0,NaN,NaN,3.04
144,3950,Branch_382,0,NaN,NaN,1.40
145,3983,Branch_282,0,NaN,NaN,2.67
146,4068,Branch_396,0,NaN,NaN,3.24
147,4081,Branch_42,0,NaN,NaN,2.03
148,4125,Branch_328,0,NaN,NaN,3.63
149,4140,Branch_428,0,NaN,NaN,3.72
150,4269,Branch_131,1,114.26,114.26,2.92
151,4281,Branch_375,0,NaN,NaN,2.80
152,4288,Branch_354,1,632.45,632.45,1.69
153,4294,Branch_16,0,NaN,NaN,1.76
154,4301,Branch_454,0,NaN,NaN,1.31
155,4326,Branch_416,0,NaN,NaN,3.21
156,4354,Branch_323,0,NaN,NaN,1.32
157,4417,Branch_293,3,694.13,231.38,3.55
158,4425,Branch_313,2,885.04,442.52,1.46
159,4430,Branch_13,0,NaN,NaN,3.26
160,4451,Branch_78,0,NaN,NaN,2.19
161,4560,Branch_216,1,772.73,772.73,4.67
162,4567,Branch_171,1,556.90,556.90,1.39
163,4588,Branch_393,0,NaN,NaN,2.01
164,4626,Branch_419,0,NaN,NaN,2.97
165,4634,Branch_266,1,630.52,630.52,2.89
166,4661,Branch_334,0,NaN,NaN,2.97
167,4715,Branch_213,0,NaN,NaN,4.74
168,4736,Branch_44,0,NaN,NaN,2.09
169,4759,Branch_326,0,NaN,NaN,2.32
170,4773,Branch_241,1,331.09,331.09,1.78
171,4785,Branch_93,0,NaN,NaN,4.48
172,4789,Branch_237,0,NaN,NaN,4.58
173,4831,Branch_22,0,NaN,NaN,1.26
174,4840,Branch_250,1,867.84,867.84,4.72
175,4908,Branch_219,0,NaN,NaN,4.60
176,4922,Branch_354,1,396.09,396.09,1.77
177,4968,Branch_65,0,NaN,NaN,1.97
178,4981,Branch_350,1,570.73,570.73,1.67
179,5049,Branch_289,1,356.52,356.52,4.83
180,5055,Branch_438,0,NaN,NaN,1.75
181,5082,Branch_246,0,NaN,NaN,1.64
182,5130,Branch_183,0,NaN,NaN,3.98
183,5134,Branch_432,1,512.03,512.03,4.10
184,5198,Branch_13,0,NaN,NaN,1.41
185,5202,Branch_380,0,NaN,NaN,3.91
186,5205,Branch_87,0,NaN,NaN,1.58
187,5225,Branch_206,1,479.91,479.91,1.35
188,5301,Branch_326,0,NaN,NaN,1.81
189,5305,Branch_434,0,NaN,NaN,3.34
190,5331,Branch_72,1,579.93,579.93,4.89
191,5346,Branch_129,0,NaN,NaN,4.11
192,5371,Branch_172,0,NaN,NaN,1.64
193,5439,Branch_307,2,"1,794.21",897.11,4.82
194,5489,Branch_340,0,NaN,NaN,3.81
195,5501,Branch_288,0,NaN,NaN,2.24
196,5504,Branch_303,1,630.25,630.25,2.97
197,5559,Branch_478,0,NaN,NaN,4.69
198,5686,Branch_275,1,138.59,138.59,4.67
199,5701,Branch_471,1,457.33,457.33,4.64
200,5735,Branch_357,0,NaN,NaN,4.26
201,5764,Branch_16,0,NaN,NaN,3.63
202,5773,Branch_55,0,NaN,NaN,1.32
203,5783,Branch_322,0,NaN,NaN,4.40
204,5796,Branch_475,0,NaN,NaN,3.11
205,5817,Branch_57,0,NaN,NaN,1.11
206,5900,Branch_387,0,NaN,NaN,2.46
207,5927,Branch_270,0,NaN,NaN,3.02
208,5941,Branch_74,0,NaN,NaN,3.47
209,5976,Branch_261,1,871.34,871.34,4.66
210,5996,Branch_98,0,NaN,NaN,3.85
211,5998,Branch_451,1,707.98,707.98,3.05
212,6004,Branch_359,1,951.33,951.33,2.79
213,6057,Branch_181,0,NaN,NaN,2.86
214,6075,Branch_353,0,NaN,NaN,1.15
215,6080,Branch_17,0,NaN,NaN,4.91
216,6094,Branch_398,0,NaN,NaN,1.64
217,6096,Branch_238,0,NaN,NaN,2.89
218,6198,Branch_92,2,647.98,323.99,3.63
219,6234,Branch_421,1,645.89,645.89,1.06
220,6264,Branch_480,0,NaN,NaN,2.59
221,6338,Branch_439,0,NaN,NaN,4.95
222,6349,Branch_321,0,NaN,NaN,3.78
223,6389,Branch_116,0,NaN,NaN,1.07
224,6392,Branch_472,2,"1,256.24",628.12,2.96
225,6447,Branch_204,0,NaN,NaN,1.11
226,6483,Branch_213,1,422.47,422.47,1.66
227,6565,Branch_74,0,NaN,NaN,3.01
228,6590,Branch_140,0,NaN,NaN,2.06
229,6593,Branch_207,1,344.69,344.69,2.47
230,6631,Branch_97,0,NaN,NaN,4.43
231,6670,Branch_199,0,NaN,NaN,2.29
232,6714,Branch_391,0,NaN,NaN,1.22
233,6747,Branch_12,2,475.97,237.99,1.45
234,6759,Branch_59,3,843.78,281.26,3.80
235,6787,Branch_108,1,347.69,347.69,1.43
236,6809,Branch_44,1,729.65,729.65,1.84
237,6837,Branch_412,0,NaN,NaN,2.62
238,6942,Branch_459,1,703.13,703.13,2.82
239,6953,Branch_339,0,NaN,NaN,2.39
240,7028,Branch_314,0,NaN,NaN,2.39
241,7063,Branch_97,0,NaN,NaN,3.56
242,7093,Branch_484,1,491.26,491.26,1.59
243,7108,Branch_320,0,NaN,NaN,4.72
244,7116,Branch_494,3,"1,830.79",610.26,2.51
245,7170,Branch_106,1,201.14,201.14,2.16
246,7177,Branch_423,3,"2,294.99",765.00,4.02
247,7207,Branch_166,0,NaN,NaN,2.38
248,7240,Branch_397,0,NaN,NaN,2.61
249,7247,Branch_398,1,82.50,82.50,4.00
250,7365,Branch_261,2,"1,260.60",630.30,3.05
251,7375,Branch_265,1,960.14,960.14,4.90
252,7376,Branch_329,0,NaN,NaN,4.16
253,7396,Branch_306,0,NaN,NaN,4.92
254,7400,Branch_207,1,388.26,388.26,3.89
255,7414,Branch_61,0,NaN,NaN,2.04
256,7429,Branch_32,1,915.90,915.90,1.81
257,7446,Branch_435,0,NaN,NaN,3.31
258,7475,Branch_327,0,NaN,NaN,2.10
259,7483,Branch_127,2,327.79,163.89,1.86
260,7525,Branch_323,0,NaN,NaN,1.22
261,7565,Branch_214,0,NaN,NaN,3.20
262,7586,Branch_140,0,NaN,NaN,2.17
263,7626,Branch_337,0,NaN,NaN,1.21
264,7675,Branch_388,0,NaN,NaN,1.61
265,7693,Branch_248,0,NaN,NaN,2.80
266,7727,Branch_166,0,NaN,NaN,3.19
267,7776,Branch_198,1,949.12,949.12,3.81
268,7779,Branch_125,0,NaN,NaN,2.21
269,7813,Branch_53,3,"1,381.40",460.47,3.88
270,7887,Branch_36,0,NaN,NaN,4.16
271,7964,Branch_212,0,NaN,NaN,4.97
272,7971,Branch_287,1,610.23,610.23,4.66
273,7978,Branch_437,1,451.50,451.50,4.68
274,8061,Branch_443,0,NaN,NaN,4.30
275,8100,Branch_313,1,906.35,906.35,1.72
276,8221,Branch_143,1,246.95,246.95,3.33
277,8258,Branch_75,0,NaN,NaN,4.97
278,8291,Branch_428,0,NaN,NaN,2.39
279,8297,Branch_498,0,NaN,NaN,2.23
280,8309,Branch_487,0,NaN,NaN,4.98
281,8313,Branch_454,0,NaN,NaN,4.58
282,8325,Branch_421,0,NaN,NaN,4.73
283,8426,Branch_269,1,393.96,393.96,3.07
284,8504,Branch_210,0,NaN,NaN,2.40
285,8505,Branch_112,0,NaN,NaN,1.97
286,8551,Branch_15,0,NaN,NaN,3.33
287,8569,Branch_306,1,358.39,358.39,2.41
288,8578,Branch_238,2,866.97,433.49,1.40
289,8598,Branch_348,0,NaN,NaN,3.38
290,8659,Branch_400,0,NaN,NaN,4.37
291,8718,Branch_191,0,NaN,NaN,4.84
292,8719,Branch_60,1,885.12,885.12,1.10
293,8738,Branch_52,0,NaN,NaN,1.01
294,8859,Branch_498,0,NaN,NaN,4.22
295,8878,Branch_487,0,NaN,NaN,2.58
296,8929,Branch_105,0,NaN,NaN,4.95
297,8942,Branch_414,0,NaN,NaN,3.62
298,8946,Branch_94,1,558.37,558.37,4.85
299,8947,Branch_187,1,132.22,132.22,2.32
300,8999,Branch_391,1,650.19,650.19,4.59
301,9025,Branch_312,0,NaN,NaN,2.02
302,9093,Branch_401,1,797.97,797.97,2.67
303,9107,Branch_260,0,NaN,NaN,4.00
304,9137,Branch_57,0,NaN,NaN,1.84
305,9150,Branch_181,1,532.57,532.57,2.79
306,9151,Branch_484,0,NaN,NaN,4.87
307,9171,Branch_426,0,NaN,NaN,2.15
308,9197,Branch_219,3,"1,135.16",378.39,2.59
309,9202,Branch_132,0,NaN,NaN,1.22
310,9217,Branch_119,0,NaN,NaN,1.34
311,9239,Branch_111,1,761.49,761.49,4.54
312,9307,Branch_216,0,NaN,NaN,1.16
313,9332,Branch_235,0,NaN,NaN,4.95
314,9386,Branch_140,0,NaN,NaN,2.00
315,9501,Branch_16,0,NaN,NaN,2.12
316,9513,Branch_408,1,328.78,328.78,3.24
317,9626,Branch_110,0,NaN,NaN,3.81
318,9641,Branch_113,2,504.96,252.48,2.19
319,9663,Branch_18,0,NaN,NaN,4.51
320,9710,Branch_494,0,NaN,NaN,3.91
321,9726,Branch_492,0,NaN,NaN,1.07
322,9735,Branch_423,1,377.89,377.89,1.64
323,9739,Branch_191,0,NaN,NaN,3.51
324,9758,Branch_46,1,369.12,369.12,1.40
325,9781,Branch_257,1,855.01,855.01,4.44
326,9787,Branch_437,0,NaN,NaN,3.94
327,9832,Branch_57,0,NaN,NaN,2.54
328,9834,Branch_176,1,926.99,926.99,4.81
329,9908,Branch_322,0,NaN,NaN,2.38
330,9912,Branch_81,0,NaN,NaN,1.59
331,9916,Branch_95,3,"1,010.59",336.86,1.15
332,9917,Branch_297,1,171.58,171.58,1.01
333,9939,Branch_333,3,"1,457.44",485.81,4.67
334,9970,Branch_436,2,"1,691.12",845.56,4.14
335,9991,Branch_142,0,NaN,NaN,2.73

## Customer Purchase Patterns

In [26]:
import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Create tables in SQLite using the previously generated DataFrames
sales_transactions.to_sql("sales_transactions", conn, index=False, if_exists="replace")
sales_line_items.to_sql("sales_line_items", conn, index=False, if_exists="replace")
product_hierarchy.to_sql("product_hierarchy", conn, index=False, if_exists="replace")

# SQL query to find products frequently bought together with frequency >= 10
query = """
SELECT
    sli1.product_code,
    st.transaction_date,
    COUNT(*) AS transaction_count
FROM
    sales_line_items sli1
JOIN
    sales_transactions st
    ON sli1.transaction_id = st.transaction_id  -- Join using transaction_id
GROUP BY
    sli1.product_code, st.transaction_date
HAVING
    COUNT(*) > 10;  -- Only consider products with more than 10 transactions on the same date
"""

# Execute the query and load it into a pandas DataFrame
result_customer_purchase_pattern = pd.read_sql(query, conn)

# Close the connection
conn.close()

In [27]:
result_customer_purchase_pattern

Empty DataFrame
Columns: [product_code, transaction_date, transaction_count]
Index: []

## Data Visualization

In [28]:
import pandas as pd

# Merge sales_line_items with sales_transactions to get transaction data
merged_sales = pd.merge(sales_line_items, sales_transactions, on='transaction_id', how='left')

# Total sales (revenue) per product
product_sales = merged_sales.groupby('product_code').agg(
    total_revenue=('total_line_amount', 'sum'),
    total_quantity=('quantity', 'sum')
).reset_index()

# Merge with product_hierarchy to get product names and categories
product_sales = pd.merge(product_sales, product_hierarchy[['product_code', 'product_name', 'category_l1', 'category_l2', 'category_l3']], on='product_code', how='left')

In [29]:
product_sales

,product_code,total_revenue,total_quantity,product_name,category_l1,category_l2,category_l3
0,P000002,"45,765.42",22,Product_2,Women's Clothing,Jackets,Casual
1,P000005,"428,246.75",146,Product_5,Children's Clothing,Jackets,Party
2,P000006,"42,192.91",20,Product_6,Men's Clothing,Sweaters,Formal
3,P000009,"186,760.51",143,Product_9,Children's Clothing,Sweaters,Casual
4,P000011,"62,292.06",38,Product_11,Women's Clothing,T-Shirts,Formal
5,P000012,"187,261.78",94,Product_12,Men's Clothing,T-Shirts,Sporty
6,P000013,"32,306.18",29,Product_13,Children's Clothing,T-Shirts,Casual
7,P000015,"24,196.02",32,Product_15,Women's Clothing,Pants,Party
8,P000016,"410,550.42",241,Product_16,Women's Clothing,Jackets,Party
9,P000017,"15,770.72",30,Product_17,Men's Clothing,Shirts,Outdoor
10,P000018,"2,910.04",4,Product_18,Children's Clothing,Jackets,Outdoor
11,P000020,"256,204.40",100,Product_20,Men's Clothing,T-Shirts,Formal
12,P000023,"124,046.43",91,Product_23,Women's Clothing,Jackets,Casual
13,P000024,"241,560.89",94,Product_24,Children's Clothing,Pants,Casual
14,P000025,"127,293.66",95,Product_25,Children's Clothing,Jackets,Party
15,P000030,"127,763.94",48,Product_30,Children's Clothing,Pants,Party
16,P000031,"140,597.26",47,Product_31,Children's Clothing,Pants,Party
17,P000034,"298,082.22",92,Product_34,Children's Clothing,Shirts,Formal
18,P000036,"96,180.49",35,Product_36,Men's Clothing,Shirts,Outdoor
19,P000038,"518,494.63",181,Product_38,Men's Clothing,Sweaters,Sporty
20,P000039,"20,395.41",30,Product_39,Men's Clothing,Pants,Casual
21,P000041,"59,795.87",13,Product_41,Women's Clothing,Jackets,Outdoor
22,P000042,"57,798.40",53,Product_42,Women's Clothing,T-Shirts,Formal
23,P000043,"61,818.39",38,Product_43,Children's Clothing,Pants,Casual
24,P000046,"274,987.70",88,Product_46,Women's Clothing,Shirts,Party
25,P000049,"337,397.92",93,Product_49,Men's Clothing,Pants,Outdoor
26,P000050,"23,744.91",39,Product_50,Women's Clothing,Pants,Casual
27,P000052,"133,356.14",80,Product_52,Men's Clothing,Pants,Party
28,P000055,"24,673.87",9,Product_55,Children's Clothing,Shirts,Sporty
29,P000057,"507,852.46",145,Product_57,Children's Clothing,Shirts,Party
30,P000059,"88,848.39",84,Product_59,Men's Clothing,Jackets,Formal
31,P000060,"70,424.85",31,Product_60,Women's Clothing,Jackets,Outdoor
32,P000062,"25,406.02",22,Product_62,Men's Clothing,Jackets,Outdoor
33,P000064,"59,382.07",24,Product_64,Men's Clothing,Sweaters,Casual
34,P000065,"67,625.04",89,Product_65,Children's Clothing,Pants,Sporty
35,P000067,"135,483.15",30,Product_67,Men's Clothing,Sweaters,Formal
36,P000068,"219,710.37",150,Product_68,Children's Clothing,Sweaters,Casual
37,P000070,"422,322.79",121,Product_70,Men's Clothing,Shirts,Party
38,P000071,"143,005.92",88,Product_71,Men's Clothing,Sweaters,Sporty
39,P000073,"40,417.80",30,Product_73,Women's Clothing,T-Shirts,Sporty
40,P000075,"30,398.05",15,Product_75,Children's Clothing,Sweaters,Formal
41,P000076,"149,305.24",70,Product_76,Children's Clothing,Pants,Sporty
42,P000078,"43,983.47",16,Product_78,Children's Clothing,T-Shirts,Party
43,P000079,"576,591.70",161,Product_79,Children's Clothing,Shirts,Formal
44,P000081,"434,695.40",98,Product_81,Women's Clothing,Sweaters,Casual
45,P000082,"141,103.82",85,Product_82,Men's Clothing,Jackets,Formal
46,P000084,"170,333.86",56,Product_84,Women's Clothing,Shirts,Sporty
47,P000085,"74,915.65",31,Product_85,Children's Clothing,Pants,Outdoor
48,P000086,"42,294.42",17,Product_86,Children's Clothing,Pants,Party
49,P000087,"183,186.30",94,Product_87,Men's Clothing,Shirts,Casual
50,P000090,"51,505.44",77,Product_90,Women's Clothing,T-Shirts,Sporty
51,P000092,"271,449.22",91,Product_92,Women's Clothing,Shirts,Sporty
52,P000093,"140,198.34",64,Product_93,Women's Clothing,Pants,Formal
53,P000094,"28,589.61",89,Product_94,Men's Clothing,T-Shirts,Formal
54,P000095,"81,227.34",73,Product_95,Children's Clothing,Jackets,Sporty
55,P000096,"11,646.53",3,Product_96,Men's Clothing,T-Shirts,Sporty
56,P000097,"92,575.60",58,Product_97,Women's Clothing,Jackets,Party
57,P000098,"84,477.17",27,Product_98,Women's Clothing,T-Shirts,Sporty
58,P000101,"36,921.71",65,Product_101,Men's Clothing,Sweaters,Outdoor
59,P000102,"24,646.26",39,Product_102,Women's Clothing,Shirts,Casual
60,P000104,"151,855.18",63,Product_104,Men's Clothing,Jackets,Sporty
61,P000105,"151,731.79",57,Product_105,Women's Clothing,Shirts,Outdoor
62,P000106,"409,425.36",129,Product_106,Children's Clothing,Pants,Party
63,P000109,"249,701.51",65,Product_109,Women's Clothing,T-Shirts,Sporty
64,P000110,"223,397.90",176,Product_110,Women's Clothing,Pants,Casual
65,P000111,"59,807.78",43,Product_111,Women's Clothing,T-Shirts,Formal
66,P000112,"13,220.70",8,Product_112,Children's Clothing,T-Shirts,Casual
67,P000113,"136,843.13",81,Product_113,Children's Clothing,Pants,Party
68,P000114,"6,721.01",3,Product_114,Men's Clothing,Shirts,Sporty
69,P000115,"152,043.88",66,Product_115,Women's Clothing,T-Shirts,Sporty
70,P000116,"58,525.33",19,Product_116,Children's Clothing,T-Shirts,Sporty
71,P000117,"80,368.22",42,Product_117,Women's Clothing,Sweaters,Casual
72,P000118,"236,736.64",145,Product_118,Men's Clothing,T-Shirts,Sporty
73,P000120,"63,022.83",67,Product_120,Women's Clothing,Shirts,Casual
74,P000122,"111,963.57",66,Product_122,Men's Clothing,Sweaters,Sporty
75,P000123,"136,439.03",118,Product_123,Women's Clothing,T-Shirts,Formal
76,P000124,"161,717.55",85,Product_124,Children's Clothing,Shirts,Party
77,P000126,"468,160.24",235,Product_126,Children's Clothing,Shirts,Casual
78,P000127,"145,632.07",47,Product_127,Children's Clothing,Shirts,Formal
79,P000128,"304,094.93",121,Product_128,Children's Clothing,Jackets,Casual
80,P000129,"3,410.77",4,Product_129,Women's Clothing,Pants,Formal
81,P000130,"278,426.01",122,Product_130,Men's Clothing,Jackets,Sporty
82,P000131,"184,881.86",101,Product_131,Women's Clothing,T-Shirts,Formal
83,P000132,"178,050.34",92,Product_132,Women's Clothing,T-Shirts,Sporty
84,P000133,"36,170.34",35,Product_133,Women's Clothing,Sweaters,Sporty
85,P000134,"199,398.74",80,Product_134,Children's Clothing,Shirts,Outdoor
86,P000135,"25,273.40",71,Product_135,Men's Clothing,Sweaters,Party
87,P000140,"91,974.07",70,Product_140,Men's Clothing,Shirts,Outdoor
88,P000141,"273,651.19",130,Product_141,Women's Clothing,Jackets,Party
89,P000142,"12,230.94",3,Product_142,Men's Clothing,Jackets,Casual
90,P000143,"300,614.49",152,Product_143,Children's Clothing,T-Shirts,Sporty
91,P000144,"62,549.03",22,Product_144,Children's Clothing,T-Shirts,Sporty
92,P000145,"107,353.04",94,Product_145,Men's Clothing,Pants,Party
93,P000146,"286,617.70",69,Product_146,Children's Clothing,T-Shirts,Party
94,P000147,"218,971.78",70,Product_147,Men's Clothing,Shirts,Party
95,P000148,"33,141.59",10,Product_148,Children's Clothing,Shirts,Sporty
96,P000149,"12,442.00",16,Product_149,Children's Clothing,Pants,Outdoor
97,P000151,"208,945.80",86,Product_151,Children's Clothing,Pants,Outdoor
98,P000153,"99,332.54",39,Product_153,Men's Clothing,Shirts,Casual
99,P000155,"65,623.39",66,Product_155,Women's Clothing,Shirts,Formal
100,P000156,"485,155.90",166,Product_156,Children's Clothing,Jackets,Sporty
101,P000157,"169,028.69",82,Product_157,Children's Clothing,Shirts,Formal
102,P000161,"124,816.85",47,Product_161,Men's Clothing,Pants,Formal
103,P000162,"208,815.16",71,Product_162,Children's Clothing,Shirts,Sporty
104,P000163,"234,436.03",97,Product_163,Children's Clothing,T-Shirts,Formal
105,P000164,"189,814.10",77,Product_164,Men's Clothing,Sweaters,Formal
106,P000165,"112,624.86",41,Product_165,Men's Clothing,Pants,Sporty
107,P000166,"355,230.61",77,Product_166,Men's Clothing,Jackets,Party
108,P000167,"12,409.46",8,Product_167,Men's Clothing,T-Shirts,Sporty
109,P000168,"136,492.03",35,Product_168,Children's Clothing,T-Shirts,Outdoor
110,P000169,"348,941.21",120,Product_169,Women's Clothing,Pants,Party
111,P000170,"82,931.40",42,Product_170,Children's Clothing,Sweaters,Sporty
112,P000171,"197,097.47",82,Product_171,Children's Clothing,Pants,Sporty
113,P000172,"14,967.65",21,Product_172,Children's Clothing,T-Shirts,Sporty
114,P000173,"401,487.76",164,Product_173,Women's Clothing,Jackets,Outdoor
115,P000174,"43,675.40",13,Product_174,Children's Clothing,T-Shirts,Formal
116,P000179,"181,430.08",93,Product_179,Women's Clothing,Pants,Sporty
117,P000180,"56,926.37",13,Product_180,Men's Clothing,Pants,Outdoor
118,P000181,"207,910.49",109,Product_181,Children's Clothing,Jackets,Sporty
119,P000182,"190,614.71",115,Product_182,Children's Clothing,Jackets,Outdoor
120,P000183,"264,579.92",93,Product_183,Men's Clothing,T-Shirts,Party
121,P000186,"89,824.94",21,Product_186,Men's Clothing,T-Shirts,Sporty
122,P000189,"98,622.33",62,Product_189,Children's Clothing,T-Shirts,Outdoor
123,P000190,"190,419.53",74,Product_190,Women's Clothing,Sweaters,Casual
124,P000194,"26,842.59",27,Product_194,Men's Clothing,Jackets,Formal
125,P000196,"79,975.90",24,Product_196,Children's Clothing,Jackets,Formal
126,P000197,"27,895.85",32,Product_197,Men's Clothing,Sweaters,Casual
127,P000198,"108,250.97",23,Product_198,Men's Clothing,Jackets,Outdoor
128,P000199,"59,127.84",30,Product_199,Men's Clothing,Shirts,Formal
129,P000200,"72,451.96",86,Product_200,Children's Clothing,Jackets,Sporty
130,P000201,"48,314.57",43,Product_201,Women's Clothing,Pants,Outdoor
131,P000202,"122,540.94",83,Product_202,Men's Clothing,Shirts,Sporty
132,P000203,"190,055.19",67,Product_203,Men's Clothing,Shirts,Casual
133,P000204,"4,916.52",2,Product_204,Women's Clothing,Shirts,Sporty
134,P000205,"42,600.10",14,Product_205,Women's Clothing,Jackets,Outdoor
135,P000206,"704,030.94",218,Product_206,Women's Clothing,Shirts,Casual
136,P000207,"532,778.29",225,Product_207,Women's Clothing,T-Shirts,Sporty
137,P000209,"203,810.91",123,Product_209,Women's Clothing,T-Shirts,Formal
138,P000210,"79,911.72",87,Product_210,Men's Clothing,Pants,Casual
139,P000211,"66,303.26",45,Product_211,Women's Clothing,T-Shirts,Party
140,P000214,"21,992.71",10,Product_214,Women's Clothing,Jackets,Party
141,P000215,"59,546.82",27,Product_215,Men's Clothing,Pants,Casual
142,P000216,"278,961.86",138,Product_216,Women's Clothing,Pants,Party
143,P000217,"24,795.73",51,Product_217,Women's Clothing,Shirts,Party
144,P000218,"377,327.70",110,Product_218,Children's Clothing,T-Shirts,Formal
145,P000219,"63,129.17",55,Product_219,Women's Clothing,Jackets,Sporty
146,P000220,"41,953.72",14,Product_220,Children's Clothing,T-Shirts,Casual
147,P000221,"152,569.03",90,Product_221,Children's Clothing,Pants,Outdoor
148,P000222,"442,793.64",209,Product_222,Men's Clothing,Sweaters,Casual
149,P000223,"363,296.33",185,Product_223,Women's Clothing,Shirts,Formal
150,P000225,"170,201.94",63,Product_225,Men's Clothing,Jackets,Sporty
151,P000228,"189,496.95",63,Product_228,Men's Clothing,Sweaters,Formal
152,P000229,"35,370.61",21,Product_229,Women's Clothing,Shirts,Formal
153,P000230,"17,295.88",22,Product_230,Women's Clothing,Pants,Outdoor
154,P000231,"7,784.08",13,Product_231,Women's Clothing,Jackets,Sporty
155,P000232,"123,544.27",38,Product_232,Children's Clothing,Jackets,Outdoor
156,P000233,"553,307.59",164,Product_233,Men's Clothing,T-Shirts,Formal
157,P000234,"216,354.75",60,Product_234,Women's Clothing,Jackets,Party
158,P000235,"182,313.50",53,Product_235,Men's Clothing,Jackets,Party
159,P000237,"332,022.50",144,Product_237,Men's Clothing,Sweaters,Party
160,P000238,"10,878.11",17,Product_238,Women's Clothing,Shirts,Casual
161,P000239,"222,805.14",96,Product_239,Men's Clothing,Sweaters,Outdoor
162,P000243,"131,925.39",98,Product_243,Children's Clothing,Sweaters,Sporty
163,P000244,"327,475.05",136,Product_244,Men's Clothing,Sweaters,Casual
164,P000245,"79,107.44",47,Product_245,Women's Clothing,Sweaters,Outdoor
165,P000247,"482,365.08",164,Product_247,Children's Clothing,T-Shirts,Sporty
166,P000248,"37,194.56",27,Product_248,Men's Clothing,Sweaters,Outdoor
167,P000249,"203,279.22",83,Product_249,Children's Clothing,Jackets,Casual
168,P000250,"65,532.02",98,Product_250,Children's Clothing,Shirts,Outdoor
169,P000251,"560,294.82",139,Product_251,Men's Clothing,Pants,Outdoor
170,P000253,"174,969.26",91,Product_253,Men's Clothing,Pants,Party
171,P000254,"108,366.71",50,Product_254,Women's Clothing,Shirts,Casual
172,P000255,"40,601.02",16,Product_255,Women's Clothing,T-Shirts,Party
173,P000256,"310,217.12",112,Product_256,Children's Clothing,Jackets,Sporty
174,P000257,"12,996.46",5,Product_257,Men's Clothing,Jackets,Formal
175,P000258,"94,569.49",47,Product_258,Men's Clothing,Sweaters,Casual
176,P000261,"154,645.00",70,Product_261,Children's Clothing,Pants,Sporty
177,P000262,"2,733.32",3,Product_262,Children's Clothing,Pants,Formal
178,P000263,"245,753.91",64,Product_263,Children's Clothing,Pants,Outdoor
179,P000264,"460,686.95",120,Product_264,Men's Clothing,Shirts,Formal
180,P000265,"486,095.17",139,Product_265,Children's Clothing,Sweaters,Party
181,P000266,"81,943.77",36,Product_266,Women's Clothing,Sweaters,Outdoor
182,P000267,"24,984.04",15,Product_267,Women's Clothing,Pants,Casual
183,P000268,"345,346.59",81,Product_268,Men's Clothing,Shirts,Party
184,P000269,"50,748.48",11,Product_269,Men's Clothing,Pants,Sporty
185,P000270,"306,235.43",143,Product_270,Children's Clothing,Sweaters,Outdoor
186,P000271,"37,273.10",13,Product_271,Women's Clothing,Pants,Casual
187,P000272,"26,492.03",14,Product_272,Women's Clothing,Shirts,Casual
188,P000274,"418,736.63",207,Product_274,Children's Clothing,Pants,Sporty
189,P000275,"34,893.96",28,Product_275,Women's Clothing,Shirts,Party
190,P000277,"108,766.82",64,Product_277,Children's Clothing,T-Shirts,Formal
191,P000279,"164,609.25",72,Product_279,Women's Clothing,Shirts,Outdoor
192,P000280,"86,346.98",29,Product_280,Children's Clothing,Sweaters,Formal
193,P000282,"13,090.80",5,Product_282,Children's Clothing,T-Shirts,Formal
194,P000283,"130,421.89",48,Product_283,Women's Clothing,Jackets,Casual
195,P000287,"32,598.12",10,Product_287,Children's Clothing,Sweaters,Formal
196,P000288,"67,134.32",16,Product_288,Men's Clothing,Shirts,Casual
197,P000289,"75,577.26",18,Product_289,Women's Clothing,Pants,Formal
198,P000290,"84,323.38",84,Product_290,Children's Clothing,Shirts,Sporty
199,P000291,"505,473.22",179,Product_291,Men's Clothing,Pants,Formal
200,P000293,"162,704.92",59,Product_293,Women's Clothing,Pants,Formal
201,P000295,"28,276.05",12,Product_295,Women's Clothing,Shirts,Party
202,P000299,"132,731.12",132,Product_299,Children's Clothing,Jackets,Outdoor
203,P000300,"50,287.42",79,Product_300,Women's Clothing,T-Shirts,Casual
204,P000301,"10,711.60",30,Product_301,Women's Clothing,Sweaters,Sporty
205,P000303,"438,764.15",135,Product_303,Men's Clothing,Shirts,Outdoor
206,P000307,"139,602.84",62,Product_307,Women's Clothing,Shirts,Casual
207,P000308,"171,429.16",109,Product_308,Women's Clothing,Sweaters,Outdoor
208,P000309,"411,903.42",137,Product_309,Men's Clothing,Sweaters,Sporty
209,P000310,"219,548.96",87,Product_310,Children's Clothing,Shirts,Sporty
210,P000311,"219,107.90",75,Product_311,Women's Clothing,Shirts,Outdoor
211,P000312,"34,719.72",89,Product_312,Women's Clothing,T-Shirts,Sporty
212,P000314,"329,823.14",175,Product_314,Women's Clothing,Sweaters,Outdoor
213,P000315,"174,206.49",127,Product_315,Women's Clothing,Jackets,Sporty
214,P000317,"174,254.79",172,Product_317,Children's Clothing,T-Shirts,Outdoor
215,P000319,"106,037.54",63,Product_319,Women's Clothing,Pants,Sporty
216,P000320,"136,539.07",37,Product_320,Children's Clothing,Pants,Outdoor
217,P000322,"114,789.31",46,Product_322,Children's Clothing,T-Shirts,Formal
218,P000324,"129,061.55",100,Product_324,Children's Clothing,Jackets,Casual
219,P000325,"12,502.55",5,Product_325,Children's Clothing,Shirts,Outdoor
220,P000326,"87,779.74",28,Product_326,Men's Clothing,Pants,Sporty
221,P000327,"69,011.04",53,Product_327,Men's Clothing,Pants,Formal
222,P000328,"245,694.80",62,Product_328,Women's Clothing,Jackets,Sporty
223,P000329,"124,174.63",45,Product_329,Women's Clothing,T-Shirts,Formal
224,P000330,"267,346.31",95,Product_330,Women's Clothing,Shirts,Formal
225,P000331,"172,149.65",66,Product_331,Children's Clothing,Jackets,Casual
226,P000332,"119,557.97",102,Product_332,Children's Clothing,Jackets,Outdoor
227,P000333,"49,699.64",82,Product_333,Children's Clothing,Jackets,Outdoor
228,P000334,"45,095.88",49,Product_334,Men's Clothing,Jackets,Outdoor
229,P000335,"112,354.63",46,Product_335,Women's Clothing,Pants,Party
230,P000336,"109,264.19",71,Product_336,Men's Clothing,Sweaters,Formal
231,P000337,"292,580.76",87,Product_337,Men's Clothing,Shirts,Formal
232,P000338,"56,400.78",24,Product_338,Women's Clothing,Shirts,Sporty
233,P000339,"14,996.88",9,Product_339,Men's Clothing,T-Shirts,Casual
234,P000341,"336,641.98",76,Product_341,Men's Clothing,Shirts,Party
235,P000344,"260,045.25",85,Product_344,Children's Clothing,Pants,Casual
236,P000346,"172,324.28",100,Product_346,Women's Clothing,Sweaters,Casual
237,P000348,"240,111.81",97,Product_348,Children's Clothing,Shirts,Casual
238,P000352,"76,398.24",44,Product_352,Men's Clothing,Jackets,Casual
239,P000353,"209,242.94",124,Product_353,Children's Clothing,Shirts,Formal
240,P000355,"21,347.35",6,Product_355,Women's Clothing,T-Shirts,Casual
241,P000356,"406,280.13",116,Product_356,Children's Clothing,Jackets,Casual
242,P000357,"2,565.17",2,Product_357,Women's Clothing,Sweaters,Casual
243,P000358,"6,662.04",5,Product_358,Women's Clothing,Shirts,Casual
244,P000359,"359,418.53",90,Product_359,Children's Clothing,Jackets,Casual
245,P000360,"375,908.08",167,Product_360,Women's Clothing,Jackets,Sporty
246,P000362,"264,157.71",171,Product_362,Women's Clothing,Sweaters,Sporty
247,P000363,"453,581.82",197,Product_363,Children's Clothing,Sweaters,Outdoor
248,P000366,"357,097.52",133,Product_366,Men's Clothing,T-Shirts,Party
249,P000367,"294,728.80",89,Product_367,Children's Clothing,Jackets,Casual
250,P000372,"180,147.68",97,Product_372,Women's Clothing,Jackets,Casual
251,P000373,"92,768.28",53,Product_373,Men's Clothing,T-Shirts,Formal
252,P000376,"143,406.38",41,Product_376,Women's Clothing,Pants,Sporty
253,P000377,"173,330.27",79,Product_377,Women's Clothing,T-Shirts,Casual
254,P000378,"88,410.92",85,Product_378,Men's Clothing,T-Shirts,Casual
255,P000379,"553,809.60",180,Product_379,Women's Clothing,Pants,Outdoor
256,P000380,"167,450.46",68,Product_380,Women's Clothing,Pants,Sporty
257,P000381,"139,029.49",79,Product_381,Children's Clothing,Pants,Formal
258,P000382,"139,012.50",59,Product_382,Men's Clothing,T-Shirts,Party
259,P000384,"266,315.40",157,Product_384,Men's Clothing,Jackets,Casual
260,P000386,"134,040.57",75,Product_386,Women's Clothing,Shirts,Sporty
261,P000388,"342,990.31",147,Product_388,Children's Clothing,Shirts,Sporty
262,P000389,"11,540.10",4,Product_389,Men's Clothing,Pants,Casual
263,P000391,"92,442.55",63,Product_391,Women's Clothing,Pants,Formal
264,P000395,"208,779.23",82,Product_395,Men's Clothing,Shirts,Formal
265,P000396,"81,554.54",23,Product_396,Men's Clothing,Shirts,Outdoor
266,P000398,"6,270.28",2,Product_398,Men's Clothing,T-Shirts,Outdoor
267,P000400,"650,639.87",271,Product_400,Men's Clothing,T-Shirts,Formal
268,P000401,"163,409.57",59,Product_401,Men's Clothing,Sweaters,Outdoor
269,P000404,"441,126.99",132,Product_404,Women's Clothing,Shirts,Formal
270,P000411,"82,454.15",26,Product_411,Men's Clothing,T-Shirts,Outdoor
271,P000412,"225,111.85",64,Product_412,Women's Clothing,Shirts,Formal
272,P000413,"41,487.67",29,Product_413,Children's Clothing,Jackets,Outdoor
273,P000414,"293,172.49",80,Product_414,Men's Clothing,Sweaters,Party
274,P000415,"244,040.70",172,Product_415,Children's Clothing,Shirts,Formal
275,P000417,"131,445.93",116,Product_417,Children's Clothing,T-Shirts,Outdoor
276,P000418,"39,500.21",47,Product_418,Men's Clothing,Jackets,Casual
277,P000419,"22,064.38",57,Product_419,Men's Clothing,Jackets,Outdoor
278,P000421,"386,226.26",188,Product_421,Men's Clothing,Pants,Casual

In [38]:
# Mengekspor DataFrame ke File Excel
product_sales.to_excel('product_sales.xlsx', index=False)

In [30]:
# Sales trends (by transaction date)
sales_trends = merged_sales.groupby('transaction_date').agg(
    total_daily_sales=('total_line_amount', 'sum'),
    total_daily_quantity=('quantity', 'sum')
).reset_index()

In [31]:
sales_trends

    transaction_date  total_daily_sales  total_daily_quantity
0         2000-02-18         293,601.33                   144
1         2000-04-11           5,121.59                     3
2         2000-04-26          62,549.03                    22
3         2000-08-12          13,507.07                     7
4         2000-09-11         401,923.77                   136
5         2000-10-22          24,635.94                    16
6         2000-11-27         126,232.88                    86
7         2000-12-09         141,587.96                    46
8         2001-01-13         245,517.46                    80
9         2001-03-16         124,662.41                    42
10        2001-04-07          97,144.55                    99
11        2001-06-02         304,343.08                    89
12        2001-06-08          17,469.07                    25
13        2001-06-15          87,552.14                    35
14        2001-07-05          54,569.46                    35
15        2001-08-26         417,964.22                   163
16        2001-09-10         166,453.98                   100
17        2001-09-18          16,872.17                    11
18        2001-09-28         119,132.46                    46
19        2001-10-08         403,482.26                   182
20        2001-10-26         126,556.54                    64
21        2001-11-22         287,481.91                    97
22        2001-11-23          39,056.89                    53
23        2001-11-27         120,469.99                   127
24        2001-12-01          86,448.90                    40
25        2001-12-14          56,926.37                    13
26        2002-02-22          37,276.97                    12
27        2002-04-24          97,406.68                    98
28        2002-05-06          12,486.00                     9
29        2002-05-08         139,449.91                    41
30        2002-07-07          43,675.40                    13
31        2002-08-13          14,569.48                    20
32        2002-08-24         410,600.28                   164
33        2002-08-29         273,790.99                   101
34        2002-09-02         310,405.69                    88
35        2002-09-24         151,731.79                    57
36        2002-10-10         131,925.39                    98
37        2002-10-12         198,181.70                    53
38        2002-12-20         108,580.51                    46
39        2003-01-01          12,409.46                     8
40        2003-01-17         324,436.16                   132
41        2003-01-27          86,421.18                    65
42        2003-03-01         109,123.25                    34
43        2003-06-06          46,766.46                    30
44        2003-08-18         116,638.32                    76
45        2003-09-11         518,527.72                   165
46        2003-10-25         123,667.18                    37
47        2003-11-03          32,265.62                    62
48        2003-11-17         220,104.36                   114
49        2003-12-18          37,687.31                    21
50        2004-02-23          95,264.96                    51
51        2004-03-27         109,235.23                    83
52        2004-04-06         465,326.30                   162
53        2004-05-28          37,194.56                    27
54        2004-05-30         245,747.78                    63
55        2004-06-08         120,738.40                    45
56        2004-07-26          48,767.93                    20
57        2004-08-02          41,067.86                    24
58        2004-08-26         292,580.76                    87
59        2004-09-30          18,931.93                    11
60        2004-10-08          12,630.62                     6
61        2004-11-16         243,050.97                   106
62        2005-01-14          36,921.71                    65
63        2005-02-10          24,196.02                    32
64        2005-02-27         306,583.64                   158
65        2005-06-18          88,722.36                    91
66        2005-07-10         127,293.66                    95
67        2005-07-22         231,785.95                   104
68        2005-08-10         106,037.54                    63
69        2005-08-17         234,335.38                   118
70        2005-09-03          79,107.44                    47
71        2005-12-07         124,046.43                    91
72        2006-02-17           7,784.08                    13
73        2006-02-24         173,072.18                    99
74        2006-03-08         336,553.01                   199
75        2006-03-20          84,477.17                    27
76        2006-05-19         219,548.96                    87
77        2006-05-24          81,227.34                    73
78        2006-06-14          28,276.05                    12
79        2006-06-15          11,646.53                     3
80        2006-07-08          12,996.46                     5
81        2006-08-09         104,239.56                    37
82        2006-09-23          64,241.68                    20
83        2006-10-04          62,992.02                    91
84        2006-11-01         234,436.03                    97
85        2006-12-20         152,381.01                    71
86        2007-01-11         213,503.28                   143
87        2007-01-23         248,677.31                   100
88        2007-02-28          37,273.10                    13
89        2007-03-11         339,253.37                   126
90        2007-03-26         338,070.07                   130
91        2007-04-06         141,103.82                    85
92        2007-05-12         195,999.25                   165
93        2007-05-26          61,856.90                    64
94        2007-06-08         125,808.77                   105
95        2007-06-15         308,514.92                   102
96        2007-06-16          22,076.04                     6
97        2007-09-07         131,608.91                    94
98        2007-09-09         698,007.76                   241
99        2007-09-11         260,532.86                   110
100       2007-09-13         177,655.62                    97
101       2007-09-19          62,292.06                    38
102       2007-09-27          42,600.10                    14
103       2007-10-02         140,597.26                    47
104       2007-11-13         425,203.67                   134
105       2007-11-16         268,237.06                   121
106       2007-12-06          54,607.26                    33
107       2008-01-03         222,305.32                   115
108       2008-02-28          76,420.58                    95
109       2008-04-09          82,030.15                    56
110       2008-04-12         501,929.46                   219
111       2008-05-12         236,414.41                    67
112       2008-06-14          26,426.57                    29
113       2008-08-17         236,290.45                    91
114       2008-09-24         293,733.32                   226
115       2008-10-01         486,492.97                   219
116       2008-10-16         251,274.18                   136
117       2009-03-09         135,483.15                    30
118       2009-03-26         128,541.43                    69
119       2009-05-28         181,903.78                    59
120       2009-06-05          75,942.04                    92
121       2009-11-03          70,048.33                    26
122       2009-11-19          64,711.11                    54
123       2009-11-29         281,772.94                   106
124       2009-12-26          97,706.70                    48
125       2010-02-05          56,479.11                    77
126       2010-02-16         174,221.55                   113
127       2010-03-08          54,804.14                    68
128       2010-04-14         412,559.66                   119
129       2010-04-22         114,757.82                   112
130       2010-04-26         193,812.87                   106
131       2010-05-31          16,719.96                     7
132       2010-06-28          85,269.44                    37
133       2010-07-08         549,865.40                   171
134       2010-07-12         219,048.16                   134
135       2010-08-07          85,139.24                    73
136       2010-08-22          63,817.18                    99
137       2010-08-27          81,389.19                    54
138       2010-10-03          39,543.38                    23
139       2010-10-04          25,406.02                    22
140       2010-11-09         179,927.47                    93
141       2010-12-24         508,723.77                   160
142       2011-01-31         172,094.91                    74
143       2011-02-18         287,199.05                   159
144       2011-05-21         246,657.58                    84
145       2011-06-01         343,165.79                   112
146       2011-06-13         310,843.13                   105
147       2011-07-05         227,331.19                    74
148       2011-09-07          52,442.40                    19
149       2011-09-09         189,710.57                    71
150       2011-11-13          51,516.46                    36
151       2012-01-18          99,117.79                    34
152       2012-07-02         121,270.18                    59
153       2012-07-08          26,492.03                    14
154       2012-07-22          59,487.19                    81
155       2012-07-25         170,201.94                    63
156       2012-07-26         517,624.78                   149
157       2012-07-30         354,173.53                    84
158       2012-08-17         154,407.07                   123
159       2012-08-26          97,048.82                    21
160       2012-09-10         148,600.25                    91
161       2012-11-15         189,997.23                    58
162       2012-11-28         300,263.70                    68
163       2012-12-30          34,719.72                    89
164       2013-01-21         234,936.03                    92
165       2013-01-31         200,117.65                   103
166       2013-04-26         216,805.32                   116
167       2013-05-26         345,527.37                   100
168       2013-06-11          85,366.31                    90
169       2013-06-29         318,684.17                   112
170       2013-07-30          67,625.04                    89
171       2013-08-05         157,225.28                    53
172       2013-08-19         238,755.18                   131
173       2013-08-28         251,426.48                   115
174       2013-08-30         268,232.71                    84
175       2013-09-23          78,328.36                    18
176       2014-01-03         238,598.49                    79
177       2014-02-09         114,698.85                    93
178       2014-03-29         150,988.37                   120
179       2014-04-19          87,297.84                    66
180       2014-04-21         399,705.12                   160
181       2014-05-04           8,195.97                     3
182       2014-05-09         254,160.10                   148
183       2014-05-11         190,372.05                    69
184       2014-07-07         241,560.89                    94
185       2014-10-24         100,700.16                    35
186       2014-12-01         145,908.41                    41
187       2014-12-05         160,460.53                    75
188       2014-12-13         115,988.77                    65
189       2014-12-14         353,610.76                   149
190       2015-02-16         137,439.62                    62
191       2015-02-20         535,548.32                   199
192       2015-02-22         566,752.29                   264
193       2015-02-28         246,557.41                    87
194       2015-05-31         168,919.92                    56
195       2015-06-10         466,000.06                   152
196       2015-06-27          81,943.77                    36
197       2015-07-02          98,366.42                    40
198       2015-07-27         215,124.29                    82
199       2015-08-03          94,569.49                    47
200       2015-10-11          82,454.15                    26
201       2015-11-02         315,682.94                    79
202       2015-11-11         183,147.06                    65
203       2015-11-25         254,283.88                   170
204       2015-12-28          81,274.79                    31
205       2015-12-29         132,464.41                    94
206       2016-01-03         643,959.07                   256
207       2016-02-17          73,090.00                    23
208       2016-02-19         171,398.72                    62
209       2016-02-26         117,775.68                    95
210       2016-03-24         199,398.74                    80
211       2016-03-25         194,993.54                    75
212       2016-06-18          46,574.37                    23
213       2016-07-03         127,440.03                    97
214       2016-07-06          67,049.83                    30
215       2016-08-17          51,092.94                    14
216       2016-10-25         148,435.19                    63
217       2016-11-18         116,474.58                    37
218       2017-03-07         244,683.29                    92
219       2017-03-29         346,358.30                    76
220       2017-04-12          59,546.82                    27
221       2017-05-01         159,615.94                    46
222       2017-05-02         512,266.67                   183
223       2017-05-22          95,474.44                    55
224       2017-07-07         173,330.27                    79
225       2017-07-31           9,362.09                     4
226       2017-09-09         208,815.16                    71
227       2017-09-22           3,410.77                     4
228       2017-12-10         173,994.67                    51
229       2017-12-19          90,797.05                    77
230       2018-01-14           6,082.03                     3
231       2018-02-26         126,464.60                    44
232       2018-03-15          96,072.38                    92
233       2018-04-28         131,053.51                    50
234       2018-07-15          50,605.28                    26
235       2018-07-19         550,038.45                   271
236       2018-07-29         430,483.71                   141
237       2018-08-18         184,199.75                    57
238       2018-09-18          13,798.19                     6
239       2018-09-26         173,623.78                   119
240       2018-10-19         156,539.86                    93
241       2019-01-07         226,980.79                   109
242       2019-02-11         140,921.58                    83
243       2019-02-12          74,915.65                    31
244       2019-02-16         264,899.88                   158
245       2019-02-19          14,889.30                    16
246       2019-02-24          34,893.96                    28
247       2019-03-01         178,050.34                    92
248       2019-03-10         148,839.29                    49
249       2019-03-29          51,505.44                    77
250       2019-04-22         245,694.80                    62
251       2019-05-19         390,207.39                   136
252       2019-06-20         530,031.40                   151
253       2019-06-23         371,314.11                   134
254       2019-07-02         134,334.82                    77
255       2019-08-21          61,267.21                    49
256       2019-09-13          12,172.00                    22
257       2019-10-07          78,140.13                    22
258       2019-10-13         367,634.51                   107
259       2019-10-15         506,913.31                   128
260       2019-11-07          65,585.06                    31
261       2019-12-09         121,014.63                    38
262       2019-12-20         417,914.59                   103
263       2020-01-03           1,350.29                     2
264       2020-01-22          85,614.78                    26
265       2020-03-10         126,447.18                    48
266       2020-05-24         123,544.27                    38
267       2020-06-26         153,462.59                    99
268       2020-08-01         133,841.31                    94
269       2020-08-06          69,394.63                    85
270       2020-09-06         223,144.68                    68
271       2020-09-19         314,383.99                   155
272       2020-10-09         177,593.04                    66
273       2020-10-12         328,612.96                    91
274       2020-12-05         199,935.43                    59
275       2020-12-14          45,959.39                    51
276       2021-01-03         125,948.31                    70
277       2021-01-27         229,828.60                    48
278       2021-04-09         251,215.12                   111
279       2021-06-03         380,673.65                   129
280       2021-07-06          24,646.26                    39
281       2021-11-27           3,226.18                     5
282       2021-12-08         149,651.62                    61
283       2022-01-03          54,629.19                    94
284       2022-01-07         103,858.84                   116
285       2022-02-13         213,936.52                    63
286       2022-02-28         117,434.98                    51
287       2022-04-02          15,315.92                    46
288       2022-04-07         145,632.07                    47
289       2022-04-09          15,770.72                    30
290       2022-04-28         338,407.30                   127
291       2022-05-04          18,927.12                    56
292       2022-06-03          17,188.00                    20
293       2022-07-08          33,141.59                    10
294       2022-07-31         124,174.63                    45
295       2022-09-09         170,042.14                    98
296       2022-09-16           4,462.05                     1
297       2022-10-05         189,290.99                    43
298       2022-11-04          57,798.40                    53
299       2023-01-08         123,682.04                    42
300       2023-01-09          38,406.20                    64
301       2023-02-01         129,061.55                   100
302       2023-03-03         216,354.75                    60
303       2023-03-04         143,406.38                    41
304       2023-05-07         129,846.65                    61
305       2023-06-02          31,289.25                    90
306       2023-06-03         258,496.63                    95
307       2023-06-09         558,039.71                   193
308       2023-06-12         297,393.35                   117
309       2023-06-21         135,074.53                    55
310       2023-07-04          57,558.12                    43
311       2023-07-23         146,437.15                    49
312       2023-09-22         273,839.01                    81
313       2023-10-07         255,906.99                   131
314       2023-10-18         454,767.78                   127

In [39]:
# Mengekspor DataFrame ke File Excel
sales_trends.to_excel('sales_trends.xlsx', index=False)

In [32]:
# Top products by revenue (filtering for the top 10)
top_products = product_sales.sort_values(by='total_revenue', ascending=False).head(10)

In [33]:
top_products

,product_code,total_revenue,total_quantity,product_name,category_l1,category_l2,category_l3
135,P000206,"704,030.94",218,Product_206,Women's Clothing,Shirts,Casual
267,P000400,"650,639.87",271,Product_400,Men's Clothing,T-Shirts,Formal
43,P000079,"576,591.70",161,Product_79,Children's Clothing,Shirts,Formal
300,P000459,"565,603.22",160,Product_459,Women's Clothing,Jackets,Party
169,P000251,"560,294.82",139,Product_251,Men's Clothing,Pants,Outdoor
255,P000379,"553,809.60",180,Product_379,Women's Clothing,Pants,Outdoor
156,P000233,"553,307.59",164,Product_233,Men's Clothing,T-Shirts,Formal
136,P000207,"532,778.29",225,Product_207,Women's Clothing,T-Shirts,Sporty
19,P000038,"518,494.63",181,Product_38,Men's Clothing,Sweaters,Sporty
29,P000057,"507,852.46",145,Product_57,Children's Clothing,Shirts,Party

In [40]:
# Mengekspor DataFrame ke File Excel
top_products.to_excel('top_products.xlsx', index=False)

In [34]:
# Customer insights - Total loyalty points earned and redeemed
customer_loyalty = sales_transactions.groupby('customer_id').agg(
    total_loyalty_earned=('loyalty_points_earned', 'sum'),
    total_loyalty_redeemed=('loyalty_points_redeemed', 'sum')
).reset_index()

In [35]:
customer_loyalty

   customer_id  total_loyalty_earned  total_loyalty_redeemed
0    CUST00001                   235                     157
1    CUST00002                   161                      81
2    CUST00003                   388                     119
3    CUST00004                   300                     185
4    CUST00005                   127                      57
5    CUST00006                   436                     166
6    CUST00007                    21                      56
7    CUST00008                   217                     139
8    CUST00009                   197                     109
9    CUST00010                   366                     141
10   CUST00011                   456                     244
11   CUST00012                   389                     134
12   CUST00013                   321                     160
13   CUST00014                   302                     103
14   CUST00015                   261                     191
15   CUST00016                   261                     133
16   CUST00017                   415                     168
17   CUST00018                   650                     191
18   CUST00019                   176                      27
19   CUST00020                   216                     141
20   CUST00021                   388                     163
21   CUST00022                    66                      72
22   CUST00023                   204                     158
23   CUST00024                   138                      65
24   CUST00025                   559                     281
25   CUST00026                   258                     183
26   CUST00027                   360                     214
27   CUST00029                   116                      66
28   CUST00030                   279                     167
29   CUST00031                    72                      32
30   CUST00032                   318                     176
31   CUST00033                   151                      83
32   CUST00034                   555                     331
33   CUST00035                    81                       2
34   CUST00036                   269                     156
35   CUST00037                   233                      65
36   CUST00038                   214                     112
37   CUST00039                    97                      20
38   CUST00040                   262                     154
39   CUST00041                   152                     171
40   CUST00042                   227                     168
41   CUST00043                    80                      19
42   CUST00044                   244                     177
43   CUST00045                   332                     182
44   CUST00046                   326                     100
45   CUST00047                   434                     174
46   CUST00048                   265                     102
47   CUST00049                   233                     122
48   CUST00050                    75                      66
49   CUST00051                   339                     145
50   CUST00052                   241                      47
51   CUST00053                   243                     203
52   CUST00054                   241                     149
53   CUST00055                   333                     101
54   CUST00056                   136                      60
55   CUST00057                   114                      37
56   CUST00058                   100                      47
57   CUST00059                   114                      93
58   CUST00060                   168                      69
59   CUST00061                   126                      32
60   CUST00062                    60                      33
61   CUST00063                   208                     175
62   CUST00064                   252                      78
63   CUST00065                   105                     102
64   CUST00066                   224                     123
65   CUST00067                   197                      83
66   CUST00068                   200                      83
67   CUST00069                    72                      23
68   CUST00070                   394                     158
69   CUST00071                   149                     102
70   CUST00072                   159                     100
71   CUST00073                   366                     203
72   CUST00074                   208                      82
73   CUST00075                   388                     192
74   CUST00076                   224                     147
75   CUST00077                   437                     253
76   CUST00078                   201                     160
77   CUST00079                   298                     173
78   CUST00080                   279                     171
79   CUST00081                    47                      47
80   CUST00082                   469                     156
81   CUST00083                   422                     233
82   CUST00084                   311                     157
83   CUST00085                   517                     219
84   CUST00086                   170                      87
85   CUST00087                   206                     119
86   CUST00089                   292                     137
87   CUST00090                   424                     201
88   CUST00091                   191                     125
89   CUST00092                   209                      92
90   CUST00093                   316                     120
91   CUST00094                    85                      58
92   CUST00095                   228                     133
93   CUST00096                   259                      87
94   CUST00097                    44                      67
95   CUST00098                   178                      91
96   CUST00099                   242                     127
97   CUST00100                   222                      40

In [41]:
# Mengekspor DataFrame ke File Excel
customer_loyalty.to_excel('customer_loyalty.xlsx', index=False)

In [36]:
# Example of how you can create a sales performance summary
sales_performance_summary = {
    "total_sales": product_sales['total_revenue'].sum(),
    "total_quantity_sold": product_sales['total_quantity'].sum(),
    "top_selling_product": top_products.iloc[0]['product_name'],
    "top_selling_category": top_products.iloc[0]['category_l1']
}

In [37]:
sales_performance_summary

{'total_sales': 53917856.45,
 'total_quantity_sold': 24138,
 'top_selling_product': 'Product_206',
 'top_selling_category': "Women's Clothing"}